spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: mongodb+srv://alifjobaer12:JobaerIslamAlif12@cluster0.xdrzlb3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true
